export {default as HomeLayOut} from './HomeLayOut'
export {default as Landing} from './Landing'
export {default as ErrorPage} from './ErrorPage'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Appointments} from './Appointments'
export {default as SingleAvailability} from './SingleAvailability'
