export {default as HomeLayOut} from './HomeLayOut'
export {default as Landing} from './Landing'
export {default as ErrorPage} from './ErrorPage'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Appointments} from './Appointments'
export {default as Availability} from './Availability'
export {default as About} from './About'
export {default as Admin} from './Admin'
export {default as AdminLanding} from './AdminLanding'
export {default as AdminInsights} from './AdminInsights'
export {default as CreatePatient} from './CreatePatient'

